# Use only for local development
version: '3.9'
services:

  db:
    restart: always
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    restart: always
    build: .
    volumes:
      - .:/opt/tickers-project  # for dev only
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
